name: helpdesk_app
description: E-Ticketing Helpdesk Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Supabase
  supabase_flutter: ^2.5.6

  # Local Storage
  shared_preferences: ^2.2.3

  # Image & File
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Launcher Icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

# Konfigurasi flutter_launcher_icons
# Jalankan setelah `flutter pub get`:
#   flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true